### ISSUE TITLE
부저 또는 LED

### ISSUE THREAD

**Issue by mintball9543** [mintball9543/RFID_raspberrypi#6]

**Comment by mintball9543** [comment]
부저로 정했고 코드구현중

**Comment by Eucliwood32** [comment]
부저  : ky-006 능동형 피에조 부저
부저와 sg90 모터가 pmw를 공유하며 동시 사용이 불가능함
스레딩이나 순차적 실행과 같은 방법이 필요하다고 생각됨 -> 함수를 만들어서 함수 실행 -> stop -> 함수실행 반복할지?
